name: Publish to AUR

on:
  push:
    tags:
      - 'v*'   # Trigger only on version tags like v0.1.0

jobs:
  aur:
    runs-on: ubuntu-latest
    container: archlinux:latest

    env:
      PKGNAME: emqutiti
      AUR_REPO: emqutiti
      VERSION: ${{ github.ref_name }}  # e.g. v0.1.0

    steps:
      # (Optional but recommended in fresh Arch containers)
      - name: Initialize pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Install deps
        run: |
          pacman -Syu --noconfirm --needed \
            base-devel git go pacman-contrib openssh curl sudo

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Strip leading v from tag
        id: v
        run: echo "version=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Bump PKGBUILD (pkgver & sha256sums)
        run: |
          ver="${{ steps.v.outputs.version }}"
          sed -i "s/^pkgver=.*/pkgver=${ver}/" PKGBUILD

          tarball="https://github.com/${GITHUB_REPOSITORY}/archive/refs/tags/v${ver}.tar.gz"
          sum=$(curl -L "$tarball" | sha256sum | cut -d' ' -f1)
          sed -i "s/^sha256sums=.*/sha256sums=('${sum}')/" PKGBUILD

      - name: Create non-root build user
        run: |
          useradd -m build
          echo 'build ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R build:build .

      - name: Generate .SRCINFO
        run: |
          sudo -u build makepkg --printsrcinfo > .SRCINFO

      # Use the secret directly; avoid ssh-agent/socket flakiness in containers
      - name: Install AUR deploy key
        run: |
          install -m 700 -d ~/.ssh
          printf '%s\n' "${AUR_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}

      # IMPORTANT: No ssh-keyscan. Accept new host key during first contact.
      - name: Clone AUR repo (resilient)
        env:
          GIT_SSH_COMMAND: >-
            ssh -4
            -o StrictHostKeyChecking=accept-new
            -o UserKnownHostsFile=/dev/null
            -o PreferredAuthentications=publickey
            -o IdentitiesOnly=yes
        run: |
          for i in $(seq 1 20); do
            git clone ssh://aur@aur.archlinux.org/${AUR_REPO}.git aur && break
            echo "clone failed (attempt $i), sleeping..."
            sleep $((i*5))
          done
          test -d aur

      - name: Commit & push to AUR (resilient)
        env:
          GIT_AUTHOR_NAME:  ${{ secrets.AUR_COMMIT_NAME || 'github-actions[bot]' }}
          GIT_AUTHOR_EMAIL: ${{ secrets.AUR_COMMIT_EMAIL || 'github-actions[bot]@users.noreply.github.com' }}
          GIT_COMMITTER_NAME:  ${{ secrets.AUR_COMMIT_NAME || 'github-actions[bot]' }}
          GIT_COMMITTER_EMAIL: ${{ secrets.AUR_COMMIT_EMAIL || 'github-actions[bot]@users.noreply.github.com' }}
          GIT_SSH_COMMAND: >-
            ssh -4
            -o StrictHostKeyChecking=accept-new
            -o UserKnownHostsFile=/dev/null
            -o PreferredAuthentications=publickey
            -o IdentitiesOnly=yes
        run: |
          ver="${{ steps.v.outputs.version }}"
          cp PKGBUILD .SRCINFO aur/
          cd aur
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add PKGBUILD .SRCINFO
          if git diff --cached --quiet; then
            echo "No changes to push."
            exit 0
          fi
          git commit -m "Release ${PKGNAME} ${ver}"
          for i in $(seq 1 20); do
            git push origin HEAD:master && break
            echo "push failed (attempt $i), sleeping..."
            sleep $((i*5))
          done
